# Generated by Django 3.2 on 2021-04-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symptom1', models.CharField(max_length=100)),
                ('symptom2', models.CharField(max_length=100)),
                ('symptom3', models.CharField(max_length=100)),
                ('prediction', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.CharField(max_length=44)),
                ('B', models.CharField(max_length=73)),
                ('C', models.CharField(max_length=67)),
                ('D', models.CharField(max_length=78)),
                ('E', models.CharField(max_length=58)),
            ],
        ),
    ]
