# Generated by Django 3.2 on 2021-04-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='prediction',
            table='prediction',
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='sheet1',
        ),
    ]
