# Generated by Django 3.2 on 2021-04-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20210414_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='id',
        ),
        migrations.AddField(
            model_name='treatment',
            name='F',
            field=models.CharField(default='', max_length=58),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='A',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='B',
            field=models.CharField(max_length=44),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='C',
            field=models.CharField(max_length=73),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='D',
            field=models.CharField(max_length=67),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='E',
            field=models.CharField(max_length=78),
        ),
    ]
