# Generated by Django 3.2 on 2021-04-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0004_alter_prediction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='name',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='prediction',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='symptom1',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='symptom2',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='symptom3',
        ),
    ]
