# Generated by Django 3.2 on 2021-04-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0005_auto_20210414_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='prediction',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prediction',
            name='prediction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prediction',
            name='symptom1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prediction',
            name='symptom2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prediction',
            name='symptom3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='prediction',
            name='symptom32',
            field=models.CharField(default='', max_length=1),
        ),
    ]
